### ISSUE TITLE
Icons not working on windows

### ISSUE THREAD

**Issue by DanielcoderX** [TorhamDev/Tlc-player#8]
`⠧ 0:00:01 <=> 0:03:52 1/1 ▶`
shown as unknown Unicode character

**Comment by TorhamDev** [comment]
use cmder terminal on windows

[cmder github](https://github.com/cmderdev/cmder)

**Comment by DanielcoderX** [comment]
Come-on ://///////

**Comment by TorhamDev** [comment]
windows default terminal does not support unicode chars you must use other terminal app
